#!/bin/sh

if [ $(pgrep -f keyboard-backlight|wc -l) -gt 3 ]; then
	exit 0
#else
#	sleep .02
fi


ceil() {
	/usr/bin/bc -lq <<-EOF
		define floor(x) {
			auto os,xx;
			os=scale;
			scale=0
			xx=x/1;if(xx>x)xx-=1
			scale=os
			return(xx)
		}
		-floor(-($*))
	EOF
}

floor() {
	/usr/bin/bc -lq <<-EOF
		define floor(x) {
			auto os,xx;
			os=scale;
			scale=0
			xx=x/1;if(xx>x)xx-=1
			scale=os
			return(xx)
		}
		floor($*)
	EOF
}

MAX=1808
NUM_STEPS=18
STEP=$(( MAX/NUM_STEPS ))
DEV='/sys/class/backlight/intel_backlight/brightness'

DZEN="dzen2 -bg #333333 -fg #13AA13 -w 300 -h 15 -x 570 -y 900 -ta c -e 'onstart=uncollapse'"
GDBAR_ARGS="-fg #EEEEEE -bg #666666 -sw 3 -ss 1 -w 240 -h 11 -s o"

draw_dzen() {
   local pipe="/tmp/monpipe"

   if [[ ! -e "$pipe" ]]; then
      mkfifo "$pipe"
      ($DZEN < "$pipe"; rm -f "$pipe") &
   fi

   (echo -n "MON   "; echo $1 $(($MAX+10)) | gdbar $GDBAR_ARGS ; sleep 2) > $pipe
}
case "$1" in
[0-9]*)
	#NEW=$(floor "($1)^2*$MAX/100" )
   NEW=$(( $1 ))
	NEW=$(( (NEW<0)?0:NEW ))
	NEW=$(( (NEW>MAX)?MAX:NEW ))
	#NEW=$1
	;;
off)
	NEW=0
	;;
on)
   NEW=$(( MAX/2 ))
	;;
down)
	OLD=$(cat $DEV)
	NEW=$(( OLD-STEP ))
	NEW=$(( (NEW<0)?0:NEW ))

	#OLD=$(ceil "sqrt(100*$(cat $DEV)/255)")
	#NEW=$(( OLD-1 ))
	#NEW=$(( NEW*NEW*255/100 ))
	#NEW=$(( (OLD<=0|NEW<0)?0:NEW ))
	;;
up)
	OLD=$(cat $DEV)
	NEW=$(( OLD+STEP ))
	NEW=$(( (NEW>MAX)?MAX:NEW ))

	#OLD=$(ceil "sqrt(100*$(cat $DEV)/255)")
	#NEW=$(( OLD+1 ))
	#NEW=$(( NEW*NEW*255/100 ))
	#NEW=$(( (OLD>=255|NEW>255)?255:NEW ))
	;;
*)
	NEW=$(zenity \
		--title "Monitor Backlight Settings" \
		--scale \
		--text="Adjust the monitor brightness to the desired level." \
		--value=$(cat $DEV) \
		--min-value="0" \
		--max-value="MAX")
	;;
esac

#echo $1 $OLD $NEW >>~/blah
echo $NEW | sudo tee $DEV &>/dev/null
draw_dzen $NEW
